apiVersion: v1
kind: Service
metadata:
    name: "prisonerscluster-9112"
    labels:
        app: "prisonerscluster-9112"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "prisonerscluster-9112"