env:
  AZURE_CONTAINER_REGISTRY: "juliuscreg"
  PROJECT_NAME: "weatherforecast"
  RESOURCE_GROUP: "Prisoners"
  CLUSTER_NAME: "prisonerscluster"
  CHART_PATH: "charts/weatherforecast"
  
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY}}.azurecr.io
        username: ${{ secrets.acr_juliuscreg_username }}
        password: ${{ secrets.acr_juliuscreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE" -f  "AzureTest.Service/Dockerfile" -t ${{ env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{env.PROJECT_NAME}}:${{ 1.0.0 }} --label dockerfile-path=AzureTest.Service/Dockerfile
        docker push ${{ env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{env.PROJECT_NAME}}:${{ 1.0.0 }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_prisonerscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: ${{ env.AZURE_CONTAINER_REGISTRY}}.azurecr.io
        container-registry-username: ${{ secrets.acr_juliuscreg_username }}
        container-registry-password: ${{ secrets.acr_juliuscreg_password }}
        secret-name: prisonerscludockerauth

    # Runs Helm to create manifest files
    - name: Bake deployment
      uses: azure/k8s-bake@v2.1
      with:
        renderEngine: 'helm'
        helmChart: ${{ env.CHART_PATH }}
        overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}
        overrides: |     
          replicas:2
        helm-version: 'latest' 
      id: bake
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          ${{ env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{ env.PROJECT_NAME }}:${{ 1.0.0}}
        imagepullsecrets: |
          prisonerscludockerauth
